pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                script{
                     String status = sh(script: "curl -sLI -w '%{http_code}' http://google.com -o /dev/null", returnStdout: true)
                        echo status
                        if(status == "200"){
                            echo "Han bhai!"
                        }
                        else{
                            echo "Na bhai!"
                        }
                }
            }
        }
    }
}
