pipeline {
    agent any

    stages {
        stage("Using curl example") {
            steps {
                script {
                   // final String url = "http://api.plos.org/search?q=title:DNA"

                  
                    // final def String response = sh(script: "curl -s $url", returnStdout: true)
                                               def jsonString = '{"name":"katone","age":5}'
        def jsonObj = readJSON text: jsonString
                      sh "echo ${jsonObj.name}"  // prints out katone
   
             
                }
            }
        }
    }
}
